### ISSUE TITLE
Diagnosing ResourceSync issues (mega ticket)

### ISSUE THREAD

**Issue by anarchivist** [ivplus/aggregator#324]
In chatting w/ @cbeer, @jermnelson and @zimeon separately, we came up with a few issues to fix/investigate further (edit this ticket to add more/track):

Upstream issues w/ the client:

* [x] resync/resync#41: [`resync/resync`](https://github.com/resync/resync)'s `resync-sync` command was getting stuck on a missing `Content-Type` header... somewhere: https://gist.github.com/anarchivist/455dffd1402fdbb1643b31d085e63d88
* [x] resync/resync#43: `resync-explore` didn't seem to work with tokens anyhow...
* [x] resync/resync#45: Access token passed to resync-sync is not exposed to resync.Client instances (was ~#329 UncaughtThrowError in proxy#show when fetching normalized MARCXML or MARC21~)

Data lake issues
* [x] Deletes delta URLs were not properly wrapped (fixed by #323 #330)
* [x] #327 Original upload and normalized ResourceLists should be Resource List Indexes 
* [x] #331  Delete delta URLs have stream ID instead of organization ID in URL

These are all blockers in addressing #309 as reraised by Harvard on the 2021-03-18 call.

**Comment by zimeon** [comment]
I think one issue is that https://pod.stanford.edu/organizations/normalized_resourcelist/marcxml is a Resource List Index and not a Resource List. The response is:

```
<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:rs="http://www.openarchives.org/rs/terms/" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
<rs:ln rel="up" href="https://pod.stanford.edu/.well-known/resourcesync/normalized-capabilitylist/marcxml"/>
<rs:md capability="resourcelist" at="2021-03-18T16:58:35Z"/>
<url>
<rs:md at="2021-01-11T12:57:56Z"/>
<loc>https://pod.stanford.edu/organizations/brown/streams/2020-11-17b/normalized_resourcelist/marcxml</loc>
</url>
....
```
when it should actually have root element `<sitemapindex....>` per http://www.openarchives.org/rs/1.1/resourcesync#ResourceListIndex

**Comment by zimeon** [comment]
Re. `Content-Length` issue -- that is a bug in `resync-sync` ... https://github.com/resync/resync/issues/41

**Comment by zimeon** [comment]
Missing access token in `resync-explorer` also a bug ... https://github.com/resync/resync/issues/43

**Comment by anarchivist** [comment]
@zimeon I think resync/resync#43 is indicative of a larger issue with `resync.Client`, which does not seem to receive the token based on your `issue-43` branch:

<details><summary>log of running resync-explorer from `issue-43`</summary>
```
li-dl-7346-0256:resync matienzo$ ./resync-explorer  --access-token "eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI1ZTEzYWMyNDRhYWE5MzIwNWI0ZmY2YWIyOThjMDVjZSIsInNjb3BlIjoiZG93bmxvYWQiLCJpc3MiOiJQT0QifQ.Ymkt5YiSaP99vGNgioHJ8WQztE3ZAyCM8nofXVE7eYI" --sitemap https://pod.stanford.edu/.well-known/resourcesync/normalized-capabilitylist/marcxml
/Users/matienzo/Documents/Code/resync/resync/explorer.py:167: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif (r.capability is 'resource'):
----- ResourceSync Explorer -----
Starting from explicit --sitemap https://pod.stanford.edu/.well-known/resourcesync/normalized-capabilitylist/marcxml

Reading https://pod.stanford.edu/.well-known/resourcesync/normalized-capabilitylist/marcxml
Parsed capabilitylist document with 1 entries:
[u] rel='up' link to https://pod.stanford.edu/.well-known/resourcesync
[1] https://pod.stanford.edu/organizations/normalized_resourcelist/marcxml
  resourcelist
Follow [number, q(uit)]?1

Reading https://pod.stanford.edu/organizations/normalized_resourcelist/marcxml
Parsed resourcelist document with 14 entries:
[u] rel='up' link to https://pod.stanford.edu/.well-known/resourcesync/normalized-capabilitylist/marcxml
[1] https://pod.stanford.edu/organizations/brown/streams/2020-11-17b/normalized_resourcelist/marcxml
[2] https://pod.stanford.edu/organizations/chicago/streams/chicago-2021-02/normalized_resourcelist/marcxml
[3] https://pod.stanford.edu/organizations/columbia/streams/03fc38d1-ba2b-4db0-92ad-c8eb60fa425f/normalized_resourcelist/marcxml
[4] https://pod.stanford.edu/organizations/cornell/streams/ff13e021-2fbb-4119-87ce-d9f9ca2857ae/normalized_resourcelist/marcxml
[5] https://pod.stanford.edu/organizations/dartmouth/streams/2021-02-09/normalized_resourcelist/marcxml
[6] https://pod.stanford.edu/organizations/duke/streams/7546b907-2e75-4f8a-b13d-daf67d18b6cf/normalized_resourcelist/marcxml
[7] https://pod.stanford.edu/organizations/harvard/streams/8e51c9a1-5df9-453f-8128-3befec88ac79/normalized_resourcelist/marcxml
[8] https://pod.stanford.edu/organizations/jhu/streams/83e87b39-9317-4fae-96c1-d277a2c2e4e0/normalized_resourcelist/marcxml
[9] https://pod.stanford.edu/organizations/mit/streams/4fcb7338-53c5-4d2f-a2f3-9d685e8fbde8/normalized_resourcelist/marcxml
[10] https://pod.stanford.edu/organizations/penn/streams/2021-03-18/normalized_resourcelist/marcxml
[11] https://pod.stanford.edu/organizations/princeton/streams/9c5ef1ad-243a-46bb-9d9d-c4fbde2a8a94/normalized_resourcelist/marcxml
[12] https://pod.stanford.edu/organizations/stanford/streams/20210221/normalized_resourcelist/marcxml
[13] https://pod.stanford.edu/organizations/yale/streams/b22453d9-8917-4c57-8a55-d3c554e1b16f/normalized_resourcelist/marcxml
[14] https://pod.stanford.edu/organizations/yultest/streams/2fb8c910-6cbb-4b94-89b2-6f1dac97c6bb/normalized_resourcelist/marcxml
Follow [number, b(ack), q(uit)]?1

Reading https://pod.stanford.edu/organizations/brown/streams/2020-11-17b/normalized_resourcelist/marcxml
HEAD https://pod.stanford.edu/organizations/brown/streams/2020-11-17b/normalized_resourcelist/marcxml
  status: 401
Follow [b(ack), q(uit)]?
```</details>

**Comment by anarchivist** [comment]
@zimeon 💬 

> I think one issue is that [pod.stanford.edu/organizations/normalized_resourcelist/marcxml](https://pod.stanford.edu/organizations/normalized_resourcelist/marcxml) is a Resource List Index and not a Resource List. 

Reported as #327.

**Comment by anarchivist** [comment]
Not sure if this is an error on our side, or in `resync` - but I think we're seeing this because of #328. 

```
li-dl-7346-0256:resync matienzo$ ./resync-sync -v --capability-list https://pod.stanford.edu/.well-known/resourcesync/capabilitylist --access-token "b0gus" -b --ignore-failures  https://pod.stanford.edu/ /tmp/pod
Reading capability list https://pod.stanford.edu/.well-known/resourcesync/capabilitylist
Reading resource list https://pod.stanford.edu/organizations/resourcelist
Read sitemap/sitemapindex from https://pod.stanford.edu/organizations/resourcelist
Parsed as sitemapindex, 14 sitemaps
Now reading 14 sitemaps
Reading sitemap from https://pod.stanford.edu/organizations/brown/streams/2020-11-17b/resourcelist (0 bytes)
Traceback (most recent call last):
  File "/Users/matienzo/Documents/Code/resync/resync/client.py", line 101, in read_resource_list
    resource_list.read(uri=uri)
  File "/Users/matienzo/Documents/Code/resync/resync/list_base_with_index.py", line 133, in read
    self.read_component_sitemap(
  File "/Users/matienzo/Documents/Code/resync/resync/list_base_with_index.py", line 179, in read_component_sitemap
    component = sitemap.parse_xml(fh=fh, sitemapindex=False)
  File "/Users/matienzo/Documents/Code/resync/resync/sitemap.py", line 212, in parse_xml
    r = self.resource_from_etree(e, self.resource_class)
  File "/Users/matienzo/Documents/Code/resync/resync/sitemap.py", line 317, in resource_from_etree
    raise SitemapParseError(
resync.sitemap.SitemapParseError: Missing <loc> element while parsing <url> in sitemap
```

**Comment by anarchivist** [comment]
Newest linked issue is #331.

**Comment by anarchivist** [comment]
Alrighty, things are working enough to get docs together. The delete deltas are a little slow to stream, so I'll create a separate issue there.
